#!/usr/bin/env python3

import cairo
import sys

width  = 297
height = 210

MM2POINTS = 72.0/25.4

###############################################################################
################################################################## helpers ####

def mm (value):
    return float(value)*MM2POINTS

###############################################################################
##################################################################### main ####

# guard: command line arguments
if len(sys.argv) != 2:
    print('Syntax: %s FILENAME' % sys.argv[0])
    print('        %s output.pdf' % sys.argv[0])
    sys.exit(1)

filename = sys.argv[1]

# initialize canvas

surface = cairo.PDFSurface(filename, mm(width), mm(height))
c = cairo.Context(surface)
c.set_line_width(mm(0.5))
c.scale(MM2POINTS, MM2POINTS)

c.move_to(10, 10)
c.line_to(110, 160)
c.set_source_rgb(0, 0, 0)
c.stroke()

