#!/usr/bin/env python3

import cairo
import sys
from math import atan, sqrt

width  = 297.0
height = 210.0
baseline = 45.0

MM2POINTS = 72.0/25.4
OUTLINE_WIDTH = 0.1
CUTLINE_WIDTH = 0.1
CUT_WIDTH     = 4.0
CUT_HEIGHT    = 2.0

###############################################################################
################################################################## helpers ####

def mm (value):
    return float(value)*MM2POINTS

def draw_shape (height):
    cutline_intersect = (swide+(snarrow-swide)/sheight*scut)/sheight*height
    
    # outline
    c.save()
    c.move_to(0, 0)
    c.line_to(swide, 0)
    c.line_to(snarrow, height)
    c.line_to(0, height)
    c.close_path()
    c.set_source_rgb(0, 0, 0)
    c.set_line_width(mm(OUTLINE_WIDTH))
    c.stroke()
    c.restore()
    
    # cutline
    c.save()
    c.move_to(0, scut)
    c.line_to(cutline_intersect, scut)
    c.set_source_rgb(1, 0, 0)
    c.set_line_width(mm(CUTLINE_WIDTH))
    c.set_dash([1.5, 0.75])
    c.stroke()
    c.restore()
    
    # cutmarks
    for x in [0, cutline_intersect]:
        c.save()
        
        # define clipping region
        c.move_to(0, 0)
        c.line_to(swide, 0)
        c.line_to(snarrow, height)
        c.line_to(0, height)
        c.close_path()
        c.clip()
        
        # draw marker
        c.move_to(x-CUT_WIDTH/2, scut)
        c.line_to(x, scut-CUT_HEIGHT/2)
        c.line_to(x+CUT_WIDTH/2, scut)
        c.line_to(x, scut+CUT_HEIGHT/2)
        c.close_path()
        c.set_source_rgb(1, 0, 0)
        c.set_line_width(mm(CUTLINE_WIDTH))
        c.stroke()
        
        c.restore()
    
    # flap
    c.save()
    c.move_to(0    , -sfbound)
    c.line_to(swide, -sfbound)
    c.line_to(swide, -sfbound-sfheight)
    c.line_to(0    , -sfbound-sfheight)
    c.close_path()
    c.set_source_rgb(0, 0, 0)
    c.set_line_width(mm(OUTLINE_WIDTH))
    c.stroke()
    c.restore()
    
    # flap boundary
    c.save()
    c.move_to(0    , -sfbound/2)
    c.line_to(swide, -sfbound/2)
    c.set_source_rgb(0, 0, 1)
    c.set_line_width(sfbound)
    c.stroke()
    c.restore()

def draw_surface_boundary (length):
    c.save()
    c.move_to(0, 0)
    c.line_to(0, length)
    c.set_source_rgb(0, 0, 1)
    c.set_line_width(ssbound)
    c.stroke()
    c.restore()

###############################################################################
##################################################################### main ####

# guard: command line arguments
if len(sys.argv) != 9:
    print('Syntax: %s HEIGHT WIDE NARROW CUT SURFACE_BOUNDARY FLAP_HEIGHT FLAP_BOUNDARY FILENAME' % sys.argv[0])
    print('        %s 130 43 25 93 10 100 5 output.pdf' % sys.argv[0])
    sys.exit(1)

sheight  = float(sys.argv[1])
swide    = float(sys.argv[2])
snarrow  = float(sys.argv[3])
scut     = float(sys.argv[4])
ssbound  = float(sys.argv[5])
sfheight = float(sys.argv[6])
sfbound  = float(sys.argv[7])
filename =       sys.argv[8]

saheight = sqrt(sheight**2 + (swide-snarrow)**2)

# initialize canvas

surface = cairo.PDFSurface(filename, mm(width), mm(height))
c = cairo.Context(surface)
c.set_line_width(mm(0.5))
c.scale(MM2POINTS, MM2POINTS)
c.translate(width/2, baseline)

for mirror in [True, False]:
    c.save()
    if mirror:
        c.scale(-1, 1)
    for i in range(2):
        if i!=0:
            draw_surface_boundary(saheight)
        c.translate(ssbound/2, 0)
        draw_shape(sheight if i==0 else saheight)
        c.translate(swide, 0)
        c.rotate(atan((swide-snarrow)/sheight))
        c.translate(ssbound/2, 0)
    c.restore()

draw_surface_boundary(sheight)
